apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: velero-internal-snapshots
spec:
  storageClassName: ${VELERO_PVC_STORAGE_CLASS}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: ${VELERO_PVC_SIZE}
