apiVersion: v1
kind: Secret
metadata:
  name: velero-s3-migration 
  labels:
    app: velero
type: Opaque
stringData:
  access-key-id: ${INTERNAL_S3_ACCESS_KEY_ID}
  secret-access-key: ${INTERNAL_S3_ACCESS_KEY_SECRET}
  object-store-cluster-ip: ${INTERNAL_S3_HOST}
